from odoo.tests.common import TransactionCase

class TestSaleInvoiceAnalytic(TransactionCase):
    def setUp(self):
        super().setUp()
        # 1) Create an analytical account
        self.analytic = self.env['account.analytic.account'].create({
            'name': 'Projecte Facturació',
        })
        # 2) Service product with analytical areas
        self.product = self.env['product.product'].create({
            'name': 'Servei X',
            'categ_id': self.env.ref('product.product_category_all').id,
            'type': 'service',
            'uom_id': self.env.ref('uom.product_uom_hour').id,
            'uom_po_id': self.env.ref('uom.product_uom_hour').id,
            'income_analytic_account_id': self.analytic.id,
            'expense_analytic_account_id': self.analytic.id,
        })
        # 3) Create a sale order with a line
        self.so = self.env['sale.order'].create({
            'partner_id': self.env.ref('base.res_partner_1').id,
            'order_line': [(0, 0, {
                'product_id': self.product.id,
                'product_uom_qty': 2,
                'price_unit': 100,
            })],
        })
        self.so_line = self.so.order_line[0]

    def test_prepare_invoice_line(self):
        """Test _prepare_invoice_line of sale.order.line"""
        # Force the call to the _prepare_invoice_line method
        template_vals = self.so_line._prepare_invoice_line()
        # It must contain the analytic_account_id field
        self.assertEqual(
            template_vals.get('analytic_account_id'),
            self.analytic.id,
            "The invoice line values dict must have the correct analytic_account_id"
        )

    def test_advance_payment_wizard(self):
        """Test _prepare_invoice_values of the advance payment wizard"""
        wizard = self.env['sale.advance.payment.inv'].create({
            'advance_payment_method': 'percentage',
            'percentage': 50,
            'order_id': self.so.id,
        })
        inv_vals = wizard._prepare_invoice_values(
            order=self.so,
            name='Advance 50%',
            amount=50,
            so_line=self.so_line,
        )
        # Check that invoice_line_ids[0][2] also has analytic_account_id
        line_vals = inv_vals['invoice_line_ids'][0][2]
        self.assertEqual(
            line_vals.get('analytic_account_id'),
            self.analytic.id,
            "The invoice line generated by the wizard must have the analytic account"
        )
