[project]
name = "odoo-addons-oca-account-analytic"
version = "17.0.20250901.0"
dependencies = [
    "odoo-addon-account_analytic_account_tag>=17.0dev,<17.1dev",
    "odoo-addon-account_analytic_distribution_manual>=17.0dev,<17.1dev",
    "odoo-addon-account_analytic_distribution_manual_date>=17.0dev,<17.1dev",
    "odoo-addon-account_analytic_distribution_model_recalculate>=17.0dev,<17.1dev",
    "odoo-addon-account_analytic_distribution_widget_rebalance>=17.0dev,<17.1dev",
    "odoo-addon-account_analytic_document_date>=17.0dev,<17.1dev",
    "odoo-addon-account_analytic_organization>=17.0dev,<17.1dev",
    "odoo-addon-account_analytic_parent>=17.0dev,<17.1dev",
    "odoo-addon-account_analytic_required>=17.0dev,<17.1dev",
    "odoo-addon-account_analytic_sequence>=17.0dev,<17.1dev",
    "odoo-addon-account_analytic_spread_by_tag>=17.0dev,<17.1dev",
    "odoo-addon-account_analytic_tag>=17.0dev,<17.1dev",
    "odoo-addon-account_move_update_analytic>=17.0dev,<17.1dev",
    "odoo-addon-analytic_base_department>=17.0dev,<17.1dev",
    "odoo-addon-analytic_partner>=17.0dev,<17.1dev",
    "odoo-addon-hr_timesheet_analytic_tag>=17.0dev,<17.1dev",
    "odoo-addon-mrp_stock_analytic>=17.0dev,<17.1dev",
    "odoo-addon-pos_analytic_by_config>=17.0dev,<17.1dev",
    "odoo-addon-product_analytic>=17.0dev,<17.1dev",
    "odoo-addon-purchase_analytic>=17.0dev,<17.1dev",
    "odoo-addon-purchase_analytic_tag>=17.0dev,<17.1dev",
    "odoo-addon-purchase_request_analytic>=17.0dev,<17.1dev",
    "odoo-addon-purchase_stock_analytic>=17.0dev,<17.1dev",
    "odoo-addon-stock_analytic>=17.0dev,<17.1dev",
    "odoo-addon-stock_analytic_rule>=17.0dev,<17.1dev",
    "odoo-addon-stock_landed_costs_analytic>=17.0dev,<17.1dev",
    "odoo-addon-stock_picking_analytic>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
