[project]
name = "odoo-addons-oca-account-analytic"
version = "19.0.20260511.0"
dependencies = [
    "odoo-addon-account_analytic_tag==19.0.*",
    "odoo-addon-account_move_update_analytic==19.0.*",
    "odoo-addon-hr_expense_analytic_tag==19.0.*",
    "odoo-addon-purchase_analytic==19.0.*",
    "odoo-addon-sale_analytic_tag==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
